[package]
name = "clip-clip"
version = "0.1.0"
edition = "2021"

[dependencies]
geo = { version = "0.28.0", features = ["serde", "use-serde"] }
geo-clipper = "0.8.0"
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"
